import crypto from "crypto";
import { getInstallationOctokit, postComment } from "../lib/github.js";
import { fetchDiff, fetchCommits } from "../lib/diff.js";
import { generateDescription } from "../lib/claude.js";

async function getRawBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

function verifySignature(rawBody, signature, secret) {
  if (!signature) return false;
  const expected = `sha256=${crypto
    .createHmac("sha256", secret)
    .update(rawBody)
    .digest("hex")}`;
  const sigBuf = Buffer.from(signature);
  const expBuf = Buffer.from(expected);
  if (sigBuf.length !== expBuf.length) return false;
  return crypto.timingSafeEqual(sigBuf, expBuf);
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).end();
    return;
  }

  const rawBody = await getRawBody(req);
  const signature = req.headers["x-hub-signature-256"];
  const event = req.headers["x-github-event"];

  if (!verifySignature(rawBody, signature, process.env.WEBHOOK_SECRET)) {
    res.status(401).json({ error: "invalid signature" });
    return;
  }

  const payload = JSON.parse(rawBody.toString("utf-8"));

  if (event !== "pull_request" || payload.action !== "opened") {
    res.status(200).json({ skipped: true });
    return;
  }

  const { repository, pull_request, installation } = payload;
  const owner = repository.owner.login;
  const repo = repository.name;
  const pullNumber = pull_request.number;
  const installationId = installation.id;

  try {
    const octokit = await getInstallationOctokit(installationId);
    const [{ diff, files }, commits] = await Promise.all([
      fetchDiff(octokit, owner, repo, pullNumber),
      fetchCommits(octokit, owner, repo, pullNumber),
    ]);

    const description = await generateDescription({ files, commits, diff });

    if (description) {
      const body = `${description}\n\n---\n*Generated by PR Description Bot*`;
      await postComment(octokit, owner, repo, pullNumber, body);
    }
  } catch (err) {
    console.error("Error generating PR description:", err);
  }

  res.status(200).json({ ok: true });
}
